// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package handlers_test

type mockDrainCounter struct {
	CountCalled chan bool
	CountOutput struct {
		Drains chan int
	}
}

func newMockDrainCounter() *mockDrainCounter {
	m := &mockDrainCounter{}
	m.CountCalled = make(chan bool, 100)
	m.CountOutput.Drains = make(chan int, 100)
	return m
}
func (m *mockDrainCounter) Count() (drains int) {
	m.CountCalled <- true
	return <-m.CountOutput.Drains
}
