// Code generated by protoc-gen-go.
// source: adapter.proto
// DO NOT EDIT!

/*
Package scalablesyslog is a generated protocol buffer package.

It is generated from these files:
	adapter.proto

It has these top-level messages:
	Binding
	ListBindingsRequest
	ListBindingsResponse
	CreateBindingRequest
	CreateBindingResponse
	DeleteBindingRequest
	DeleteBindingResponse
*/
package scalablesyslog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Binding struct {
	AppId    string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	Drain    string `protobuf:"bytes,3,opt,name=drain" json:"drain,omitempty"`
}

func (m *Binding) Reset()                    { *m = Binding{} }
func (m *Binding) String() string            { return proto.CompactTextString(m) }
func (*Binding) ProtoMessage()               {}
func (*Binding) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Binding) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Binding) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Binding) GetDrain() string {
	if m != nil {
		return m.Drain
	}
	return ""
}

type ListBindingsRequest struct {
}

func (m *ListBindingsRequest) Reset()                    { *m = ListBindingsRequest{} }
func (m *ListBindingsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBindingsRequest) ProtoMessage()               {}
func (*ListBindingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListBindingsResponse struct {
	Bindings []*Binding `protobuf:"bytes,1,rep,name=bindings" json:"bindings,omitempty"`
}

func (m *ListBindingsResponse) Reset()                    { *m = ListBindingsResponse{} }
func (m *ListBindingsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBindingsResponse) ProtoMessage()               {}
func (*ListBindingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListBindingsResponse) GetBindings() []*Binding {
	if m != nil {
		return m.Bindings
	}
	return nil
}

type CreateBindingRequest struct {
	Binding *Binding `protobuf:"bytes,1,opt,name=binding" json:"binding,omitempty"`
}

func (m *CreateBindingRequest) Reset()                    { *m = CreateBindingRequest{} }
func (m *CreateBindingRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBindingRequest) ProtoMessage()               {}
func (*CreateBindingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateBindingRequest) GetBinding() *Binding {
	if m != nil {
		return m.Binding
	}
	return nil
}

type CreateBindingResponse struct {
}

func (m *CreateBindingResponse) Reset()                    { *m = CreateBindingResponse{} }
func (m *CreateBindingResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateBindingResponse) ProtoMessage()               {}
func (*CreateBindingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteBindingRequest struct {
	Binding *Binding `protobuf:"bytes,1,opt,name=binding" json:"binding,omitempty"`
}

func (m *DeleteBindingRequest) Reset()                    { *m = DeleteBindingRequest{} }
func (m *DeleteBindingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteBindingRequest) ProtoMessage()               {}
func (*DeleteBindingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteBindingRequest) GetBinding() *Binding {
	if m != nil {
		return m.Binding
	}
	return nil
}

type DeleteBindingResponse struct {
}

func (m *DeleteBindingResponse) Reset()                    { *m = DeleteBindingResponse{} }
func (m *DeleteBindingResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteBindingResponse) ProtoMessage()               {}
func (*DeleteBindingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Binding)(nil), "scalablesyslog.Binding")
	proto.RegisterType((*ListBindingsRequest)(nil), "scalablesyslog.ListBindingsRequest")
	proto.RegisterType((*ListBindingsResponse)(nil), "scalablesyslog.ListBindingsResponse")
	proto.RegisterType((*CreateBindingRequest)(nil), "scalablesyslog.CreateBindingRequest")
	proto.RegisterType((*CreateBindingResponse)(nil), "scalablesyslog.CreateBindingResponse")
	proto.RegisterType((*DeleteBindingRequest)(nil), "scalablesyslog.DeleteBindingRequest")
	proto.RegisterType((*DeleteBindingResponse)(nil), "scalablesyslog.DeleteBindingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Adapter service

type AdapterClient interface {
	ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error)
	CreateBinding(ctx context.Context, in *CreateBindingRequest, opts ...grpc.CallOption) (*CreateBindingResponse, error)
	DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error)
}

type adapterClient struct {
	cc *grpc.ClientConn
}

func NewAdapterClient(cc *grpc.ClientConn) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error) {
	out := new(ListBindingsResponse)
	err := grpc.Invoke(ctx, "/scalablesyslog.Adapter/ListBindings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) CreateBinding(ctx context.Context, in *CreateBindingRequest, opts ...grpc.CallOption) (*CreateBindingResponse, error) {
	out := new(CreateBindingResponse)
	err := grpc.Invoke(ctx, "/scalablesyslog.Adapter/CreateBinding", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error) {
	out := new(DeleteBindingResponse)
	err := grpc.Invoke(ctx, "/scalablesyslog.Adapter/DeleteBinding", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Adapter service

type AdapterServer interface {
	ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error)
	CreateBinding(context.Context, *CreateBindingRequest) (*CreateBindingResponse, error)
	DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error)
}

func RegisterAdapterServer(s *grpc.Server, srv AdapterServer) {
	s.RegisterService(&_Adapter_serviceDesc, srv)
}

func _Adapter_ListBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).ListBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalablesyslog.Adapter/ListBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).ListBindings(ctx, req.(*ListBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_CreateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).CreateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalablesyslog.Adapter/CreateBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).CreateBinding(ctx, req.(*CreateBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_DeleteBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).DeleteBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalablesyslog.Adapter/DeleteBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).DeleteBinding(ctx, req.(*DeleteBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Adapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scalablesyslog.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBindings",
			Handler:    _Adapter_ListBindings_Handler,
		},
		{
			MethodName: "CreateBinding",
			Handler:    _Adapter_CreateBinding_Handler,
		},
		{
			MethodName: "DeleteBinding",
			Handler:    _Adapter_DeleteBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adapter.proto",
}

func init() { proto.RegisterFile("adapter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x9b, 0x56, 0x90, 0x72, 0xa1, 0x0c, 0x26, 0x55, 0xa3, 0x4c, 0x95, 0x01, 0xa9, 0x53,
	0x24, 0xda, 0x27, 0xe0, 0x67, 0xa9, 0x60, 0x21, 0x2b, 0x12, 0x92, 0x43, 0xae, 0x4a, 0xa4, 0x60,
	0x9b, 0x5c, 0x33, 0xf0, 0x42, 0x3c, 0x27, 0x6a, 0xec, 0x56, 0xcd, 0x8f, 0xc2, 0xc2, 0x78, 0xed,
	0x73, 0xbf, 0xe3, 0x73, 0x12, 0x98, 0x88, 0x4c, 0x68, 0x83, 0x65, 0xac, 0x4b, 0x65, 0x14, 0x3b,
	0xa7, 0x37, 0x51, 0x88, 0xb4, 0x40, 0xfa, 0xa6, 0x42, 0x6d, 0xf8, 0x33, 0xf8, 0x77, 0xb9, 0xcc,
	0x72, 0xb9, 0x61, 0x01, 0x1c, 0x09, 0xad, 0xd7, 0x59, 0xe8, 0xcd, 0xbd, 0xc5, 0x49, 0x62, 0x07,
	0x16, 0xc1, 0xf8, 0x5d, 0x91, 0x91, 0xe2, 0x03, 0xc3, 0x61, 0x75, 0xb1, 0x9f, 0xb7, 0x1b, 0x59,
	0x29, 0x72, 0x19, 0x8e, 0xec, 0x46, 0x35, 0xf0, 0x29, 0x5c, 0x3c, 0xe5, 0x64, 0x1c, 0x96, 0x12,
	0xfc, 0xfc, 0x42, 0x32, 0xfc, 0x11, 0x82, 0xfa, 0x31, 0x69, 0x25, 0x09, 0xd9, 0x0a, 0xc6, 0xa9,
	0x3b, 0x0b, 0xbd, 0xf9, 0x68, 0x71, 0xba, 0x9c, 0xc5, 0xf5, 0x47, 0xc6, 0x6e, 0x27, 0xd9, 0x0b,
	0xf9, 0x1a, 0x82, 0xfb, 0x12, 0x85, 0xc1, 0xdd, 0x95, 0x35, 0x61, 0x37, 0xe0, 0x3b, 0x4d, 0x95,
	0xa2, 0x87, 0xb5, 0xd3, 0xf1, 0x19, 0x4c, 0x1b, 0x28, 0xfb, 0xb0, 0xad, 0xc7, 0x03, 0x16, 0xf8,
	0x4f, 0x1e, 0x0d, 0x94, 0xf5, 0x58, 0xfe, 0x0c, 0xc1, 0xbf, 0xb5, 0x1f, 0x88, 0xbd, 0xc0, 0xd9,
	0x61, 0x41, 0xec, 0xb2, 0x89, 0xed, 0x68, 0x35, 0xba, 0xea, 0x17, 0xb9, 0x28, 0x03, 0xf6, 0x0a,
	0x93, 0x5a, 0x4a, 0xd6, 0x5a, 0xec, 0xea, 0x33, 0xba, 0xfe, 0x43, 0x75, 0xc8, 0xaf, 0x25, 0x6c,
	0xf3, 0xbb, 0xba, 0x6c, 0xf3, 0x3b, 0x6b, 0xe2, 0x83, 0xf4, 0xb8, 0xfa, 0x7d, 0x57, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xba, 0x87, 0x9a, 0x05, 0xcf, 0x02, 0x00, 0x00,
}
