// Code generated by go-bindata.
// sources:
// scalable-syslog-certs/adapter-rlp.crt
// scalable-syslog-certs/adapter-rlp.csr
// scalable-syslog-certs/adapter-rlp.key
// scalable-syslog-certs/adapter.crt
// scalable-syslog-certs/adapter.csr
// scalable-syslog-certs/adapter.key
// scalable-syslog-certs/fake-log-provider.crt
// scalable-syslog-certs/fake-log-provider.csr
// scalable-syslog-certs/fake-log-provider.key
// scalable-syslog-certs/loggregator-ca.crl
// scalable-syslog-certs/loggregator-ca.crt
// scalable-syslog-certs/loggregator-ca.key
// scalable-syslog-certs/scalable-syslog-ca.crl
// scalable-syslog-certs/scalable-syslog-ca.crt
// scalable-syslog-certs/scalable-syslog-ca.key
// scalable-syslog-certs/scheduler.crt
// scalable-syslog-certs/scheduler.csr
// scalable-syslog-certs/scheduler.key
// DO NOT EDIT!

package app_test

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _adapterRlpCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEKzCCAhOgAwIBAgIRANLx2BrOxQhHCBjR2I7p6rwwDQYJKoZIhvcNAQELBQAw
GTEXMBUGA1UEAxMObG9nZ3JlZ2F0b3ItY2EwHhcNMTcwMjE2MjEwODAxWhcNMTkw
MjE2MjEwODAxWjAWMRQwEgYDVQQDEwthZGFwdGVyLXJscDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBALseM3TgU+ee51Fn6D6fYbwsZDm5Xe3qoC4ECFLH
J33nd2K7doa3wAKJXgZsRvVVGN5q4YH/XAzHS18OYpuTvh+euXLeATEIRk/7Xqkl
8hW6Q1vloXK8b3BLzg4zvQK3YstnV4Ax2/yyteEVC3K3bj4H1x8vMLO8DHBwsGhf
BQuOd2tXEgA3j4Rh7ZqAclymuhToD4iAvq1vLDyZKzk2v3zfyeAthucxcXAgf8sE
m2D3CgZJQsUiBEXZrTJ8eb9UEg9jR/AokyX/r6neybE0L+FyPkJJeRV+2iwa8lu9
6FGBcwn/VUUkK867w4yPtWbFKv1W9vb8U6xY8JK2q5fBckcCAwEAAaNxMG8wDgYD
VR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNV
HQ4EFgQURcDpY1KJcvtwMce3QEgKaiM5/0QwHwYDVR0jBBgwFoAUi0uZDZa+H/UI
sFItwZfl8E1ts0kwDQYJKoZIhvcNAQELBQADggIBAEcg3Z+cSsMb/PE5BNW92xCS
bXoVos11gH5KuiuYQAovilhntyUeCr2q0Zozmii8UGcDlszMRcvMqXWnQa1Ae10E
oQBA0oJAFyrOBdJ0hVMREdBdYZZIm0UcyQXv6rY7mhV746UywunQe5xw2CyMA+vY
/6tI45aUm47L7oTYm/58+eMV4q3nAyq9MsutlWOkEt23n9GQZvLUz55ihq34MqED
JG+shtE5D646Jq+pebSyIKD09HrOcEEqCVfQrFlJ65adve1XssHbyYx86FQyJ1fJ
nvXi2EfE5BJyfVwsgKee3Rfs+L1Du4iLjIgEqC8crxAgB1dlaRk87AezicNhk+wE
84G7p7DPaWN6gVFjerSeb/0vTz/zLot/s49iAFTWZDJBGQQdc+synEhlRgUR8KMI
zYCI0sOxwq8DefUzKQq4GE/YYQBE1CwMpQOv71x3BLEtlxmxfLA+vir3YYPKIG1L
3xHBEEO2zjnVS3DeJcSZch8UVguICqmeFrKH/CZ3s/9a18dALeu6lYfiEg86YJQl
Ci2+x3FQPr23r5dRcmiLBTKfPvJDM4LEQEEMo0VbFBblFu00co5eEMrh16VzZ0xF
S+kyKT2OD5wPEN+WtcawoX1X2pVokpU6SmzWq85olfAMs1QGyNjUocmILDWDK9Vx
Y1VzltWd5io/ywJdnkN1
-----END CERTIFICATE-----
`)

func adapterRlpCrtBytes() ([]byte, error) {
	return _adapterRlpCrt, nil
}

func adapterRlpCrt() (*asset, error) {
	bytes, err := adapterRlpCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "adapter-rlp.crt", size: 1505, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _adapterRlpCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICWzCCAUMCAQAwFjEUMBIGA1UEAxMLYWRhcHRlci1ybHAwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQC7HjN04FPnnudRZ+g+n2G8LGQ5uV3t6qAuBAhS
xyd953diu3aGt8ACiV4GbEb1VRjeauGB/1wMx0tfDmKbk74fnrly3gExCEZP+16p
JfIVukNb5aFyvG9wS84OM70Ct2LLZ1eAMdv8srXhFQtyt24+B9cfLzCzvAxwcLBo
XwULjndrVxIAN4+EYe2agHJcproU6A+IgL6tbyw8mSs5Nr9838ngLYbnMXFwIH/L
BJtg9woGSULFIgRF2a0yfHm/VBIPY0fwKJMl/6+p3smxNC/hcj5CSXkVftosGvJb
vehRgXMJ/1VFJCvOu8OMj7VmxSr9Vvb2/FOsWPCStquXwXJHAgMBAAGgADANBgkq
hkiG9w0BAQsFAAOCAQEAYzbPnEgiaDCR3HBmzDLkkMm3mbD8wem5V3zZw0lo4+2o
dWH0pnLDNzxXNZ3vRY/2fd3mWvUk/voWQiks9ZdF97OLroT9Ygdy78RCworKGqPz
F6ZKzVmg2iCjJaun6PCN7NzLQmzn+t/SrjwqoGOh86hcMj9vW13P5NOyYpjDebOn
Kl3aSK89rts8tlR/e1yBYnJmgbmd8gSvbaxiXqtFWI80C5/daPVZckeQVAbfp+k/
2/aZ0yw7fosxgYmC9JZTWrTjxGQAr5uZHE/V6vpYjDSWaYjcff//aaXVJmi5nZSZ
6pfumHbQy5VGi3ddUcqRD9n3Lum+Y7ei+dnj0YPPKQ==
-----END CERTIFICATE REQUEST-----
`)

func adapterRlpCsrBytes() ([]byte, error) {
	return _adapterRlpCsr, nil
}

func adapterRlpCsr() (*asset, error) {
	bytes, err := adapterRlpCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "adapter-rlp.csr", size: 895, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _adapterRlpKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAux4zdOBT557nUWfoPp9hvCxkObld7eqgLgQIUscnfed3Yrt2
hrfAAoleBmxG9VUY3mrhgf9cDMdLXw5im5O+H565ct4BMQhGT/teqSXyFbpDW+Wh
crxvcEvODjO9Ardiy2dXgDHb/LK14RULcrduPgfXHy8ws7wMcHCwaF8FC453a1cS
ADePhGHtmoByXKa6FOgPiIC+rW8sPJkrOTa/fN/J4C2G5zFxcCB/ywSbYPcKBklC
xSIERdmtMnx5v1QSD2NH8CiTJf+vqd7JsTQv4XI+Qkl5FX7aLBryW73oUYFzCf9V
RSQrzrvDjI+1ZsUq/Vb29vxTrFjwkrarl8FyRwIDAQABAoIBAQC5M8E2czpYzFyj
pDaolNQFjeJ9h81CSLHWGcOrOtcJtOnjXSyJVqHDYPchYFYzSNDeg+dD5d3UAAXH
xdMvrWHGpjFjUfzX7Rq620/sF1Su0LcO5A+SIpQiD8WZJPh1EdHFBToD9lWIndGL
QGseVhPVbaksgmav3vZo7ACOrU2vCtZsyye8UGDxREZOIn1tHC1HDR/VOx/5FX9u
gODBMaVao0n4QJmP9G9DPISND60zHwWhW+Y/D8fypPqeCYnbwQ5iOn45VzljWBOq
wo0yZPNZM6DAAfSbG/RcVuuu11ZDdlXjlkvzqHcOpc+ey6s8/DI/27k63ulVR6YV
wavUj1NRAoGBAMehxI1H3wHl1Y/yMdEO3EplgqDBxqi4sG3LqggWBu4f63jMy18P
9oc/Zpz2ozwwplCxNi+vRb5dqUyle81zjWSV9HcZK4pcjvpIZkYkBf7ZovtqCys1
kY6E74QlYNKkY3SxEZHxyySXlN3+sUPROg5HLIiJyTIwXT1EAw4m3Q17AoGBAO/z
36YOHu2L9oHgsWhC5lRMfi6qlXjtkHrYBJ4Y7I7Iauzjop693IXuqTNfmYHYN++1
AJsk/djEHw3zz5Xt8jE49TIVqZ28s+g9vsuIoB93sRn1mnBlNY9P8+LRyNSP5u7k
jwPQK0rM7AEnfzpaVrpgwOsxI80pGcy3zOwWfqalAoGBALxoNDSSjCoiW/hKwDFq
MQYV378QowlBpWE6QfL3tvquLXII9jd1vVnPwGyLaWu5Dn5Bgb5nUQ9lHg80by9r
yxoPXHW6z5j52gbkpYG1JeNsS6G0Z24UVJeJZvP0wviKJUNQiiCPbwXN+bW6VlqG
8J/hFGqYf8ZaVuUndyq4CxBZAoGAScabvvycecEM28XwBfR7yPNz4HlGV9YDFCIS
2WEkaooohgk/WLtbcDp+/3KnSgrmt+bY9tqayekS+0E5VAnC62ttyCZs7ji0v/Us
EnxBbytn4mlnQKN9okCc5eJGc0SDZnQTnMKGbQswjPJN5e0cuVVCO43ySgQXEKB6
eyQ3cJkCgYAMSRyKv2UE+PDcSnMuZ6V4XUnsqmMdovoAlRFwIvZ95FyObWFbYnz/
bMv+j+WRq5e1bjMKCthUJ1OAKW8koNH22+uQySOqnYZAlsXts21D8rNbDLqDNc29
aU24UFmLWm07SIGjMFtufafk44Y+wIQGDtmzY3EjvwcMvObwIXmmnA==
-----END RSA PRIVATE KEY-----
`)

func adapterRlpKeyBytes() ([]byte, error) {
	return _adapterRlpKey, nil
}

func adapterRlpKey() (*asset, error) {
	bytes, err := adapterRlpKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "adapter-rlp.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _adapterCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEKzCCAhOgAwIBAgIRAPT+anYoDZPcjXu3Wew5sXcwDQYJKoZIhvcNAQELBQAw
HTEbMBkGA1UEAxMSc2NhbGFibGUtc3lzbG9nLWNhMB4XDTE3MDIxNjIxMDgwMVoX
DTE5MDIxNjIxMDgwMVowEjEQMA4GA1UEAxMHYWRhcHRlcjCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBANVFQYtCKtipkqNIkfPWhowZdEXXXxq2x8k7bnEf
MnZ9FpCQf0dhDKe2wIduiAoNL0DoCggmYLoKvb/i0ky6sxLH6ltQqNQETVP869Ds
hk1dGbYlHYbY4RXU9f4FfjqHnsIzW1vUnlxY/Z0PwCBk20BZ3oqXolUHYcdKsEOk
nCmCRBQQe4tPmux6pHpnyuxb0LqvFy/fafrpE2QcoD+xs0sqciTyRCHaJhDantHG
tdFaDv166DU2M2RSW5UgHFEvAmYNIQAlFoCXIG6in2pe7TiWArFFnRHw6oZHooZs
OOogfZ4qDasTSRknwuKcJpa4ZsW0mSUkiqLIJhXpBGCJHucCAwEAAaNxMG8wDgYD
VR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNV
HQ4EFgQUMTNDx80C4KzFFhxSfaw7V0kQKWAwHwYDVR0jBBgwFoAUzgBX7nTmxWuA
yn6tTTSMl7eN27AwDQYJKoZIhvcNAQELBQADggIBAKR+cG5nBcHpW9K/ImATbWCs
jlrfwHfyKFxG62+hu7EXTX5TzYsrJyocGMED9TEnBeeAeFRATou/fSFhcXrLgBQg
MME/MEsjW1RuFWRJWhS5bf1RMFcOFvB3EsniP1tMs9a7hSVX7DfrPBbxNCnGoVj+
DNNa9esPu8ywnY/vWEwkUvK6hlvXCitPETRpwXwR0jft9pGhz0nEnzMSev1/VtM1
kEBM8LOZij/oFTQteRF1OUtR/Bor4TYU8n4J2ZlorKezpS2OvGc7c5asug4N9G6M
lM6QhSb03uzijF1Shpw+dO6bC9WzIb4PcVcSPAzAXcgsH9LC2HeNE+U3rgPOipIm
AnYwdK02T8vy4I4xf0ndLVm2TU9GgAf7IZdp1jo1pNwMPkoSbkrBHo+r/E6ENNYq
uvXy371+DXvkFfE0D4WnWc+Xa5w92Q8TthVSsQil6uSEd9OLkIEjFPBXiMObhTiE
XzdDTRvzdwCx9tJriZjkjxecwouAczqJdiAO6xq6jlEkKnx1HhAKXKV4uKr0Iyk9
kD/wRKF+hp9pcHD+Do2G9BXq6HkxMalLSAYmD2ZZKFUg7xrE/ZN8vA31VvxrGeqq
77qfVJf1xEOegPJEkb8Sq19f8jAcqrRqYy6MGzC2uDVPR4St9tFRWyIat/uk3dIx
hW7S7JCRtAYcUll3Z7LO
-----END CERTIFICATE-----
`)

func adapterCrtBytes() ([]byte, error) {
	return _adapterCrt, nil
}

func adapterCrt() (*asset, error) {
	bytes, err := adapterCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "adapter.crt", size: 1505, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _adapterCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVzCCAT8CAQAwEjEQMA4GA1UEAxMHYWRhcHRlcjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANVFQYtCKtipkqNIkfPWhowZdEXXXxq2x8k7bnEfMnZ9
FpCQf0dhDKe2wIduiAoNL0DoCggmYLoKvb/i0ky6sxLH6ltQqNQETVP869Dshk1d
GbYlHYbY4RXU9f4FfjqHnsIzW1vUnlxY/Z0PwCBk20BZ3oqXolUHYcdKsEOknCmC
RBQQe4tPmux6pHpnyuxb0LqvFy/fafrpE2QcoD+xs0sqciTyRCHaJhDantHGtdFa
Dv166DU2M2RSW5UgHFEvAmYNIQAlFoCXIG6in2pe7TiWArFFnRHw6oZHooZsOOog
fZ4qDasTSRknwuKcJpa4ZsW0mSUkiqLIJhXpBGCJHucCAwEAAaAAMA0GCSqGSIb3
DQEBCwUAA4IBAQArdnpi4ZLXadjBFcRxkMIn0kDs1c+VjknsVRRj9gxhALJ3KHLV
kNqXBOAci3wjp7XPzeQjqHpR0eTOG3uhS3b3ipycEK3LJq+BTjOgz5pv3NUmvPoF
U/MDYU0be11z6A+fiGiElc8BBXouSC58Z+Pfm+QWjLES8/MmCRs5/P/XMEEk2r1t
bPBm3giBYezbzWQCgUVwIwpdvF6JqP+gj43CtKB+AJhvIQGL+XCEZ0fwcfHZy45r
ffN69noKthI1rV/Pg14mTj9Ao9aOn7sNrbqUndmSbXftZe8NAVznM+VSvZ8afHIi
fj6OAmrvIQHxtuczAyfh9c8QB277NhQA6oy7
-----END CERTIFICATE REQUEST-----
`)

func adapterCsrBytes() ([]byte, error) {
	return _adapterCsr, nil
}

func adapterCsr() (*asset, error) {
	bytes, err := adapterCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "adapter.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _adapterKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA1UVBi0Iq2KmSo0iR89aGjBl0RddfGrbHyTtucR8ydn0WkJB/
R2EMp7bAh26ICg0vQOgKCCZgugq9v+LSTLqzEsfqW1Co1ARNU/zr0OyGTV0ZtiUd
htjhFdT1/gV+OoeewjNbW9SeXFj9nQ/AIGTbQFneipeiVQdhx0qwQ6ScKYJEFBB7
i0+a7HqkemfK7FvQuq8XL99p+ukTZBygP7GzSypyJPJEIdomENqe0ca10VoO/Xro
NTYzZFJblSAcUS8CZg0hACUWgJcgbqKfal7tOJYCsUWdEfDqhkeihmw46iB9nioN
qxNJGSfC4pwmlrhmxbSZJSSKosgmFekEYIke5wIDAQABAoIBACOsK+RxMt1+r6pk
LxWMIoE4mLw95AiB3jUIndaKE1TCY43WvZNg5k7/QIDmuhaEUg0XQuZOFQvJVCfO
dsKiz+UqT0bq3PJprc2IlqEhju1Nz0kqOCAgErYmIudUX+LGYIW3NWbMz5g+wl0N
D2Pbutiur4ybBGoYjABbu9P0qrI+a52LfLY0h+k9p8YF6E++DG2eSJqU10v6r2Oy
UfqKeEh4U7XOLuRIAnX2CxaYFQTwzd1xcRM4l4uSnx+JCzxwpMem198tzXN0FBJ0
1y2EbwVjQD339cyqmfDdkHEgCj8CnYf/e2fLWB/qzMdV2FSOmZ+emczOUwuGPO+F
rQxsvqECgYEA6wS4eYWmSAMgnWtPycY1oaQE6o2zznRrKCdbskRQr4KqH/+4a1Tl
fZSy65ZQuywz3CkDejLJLhItzBfLV6CHt/131QPGLa0vJtf+Iggyg52PMm63Djux
pNk5/el8oXGea0eilTktTSQRXSC9RvH/2SnAn5kTAo1eUGmO/gO6ZJkCgYEA6E9+
QTk+UNycX8800JUFz+hoi80/OitSE3FmI6DB3Y4afu8kWHCAeyIjqKlhn7rTRnDn
X7Ojplyx1RQ8pkvFA7ABtuWtyFXSkirGdERuKcL0X3s1Hq3iE/IY9lV2lsrVAqFU
bxLhFPZ3k/5vTIHzBp8Tv7zrv87zGGBMd2/2T38CgYAOrmbPwJeYnAlnjBKZ6jXj
eRmNhXicBw3CnmLOChJ4RFNYWGMu4UjMxYM/0E4Owz4iHLXI5m9G33/Y5guf17li
twTLW8b/h3gQlyGbAqQVMLyHS/9Hdlcskx1aTUGp3C0nSnxPkhjQXtZu2OK6EdgH
uuH7llZnrGkd4No76AO20QKBgQDmCADemM4px6lX/Zcwir+MlXcgJ4ZaFRdahUk8
MiyFM/bsheQZZpzyUGW61q4COj6GW7nfu8NqMhMtCLLdf91/v0KTVm50FvdBIPYN
nszusUrFWPzKeieI1Ir/MLUSr5mo1xMCQVF7LmpNsv2GZo68mbw2ed1+um9gTcqp
4cWmBQKBgB5yA67peVzCkqRpPfWo6R2RcQFjDuIb8LvX3qs0D4YEpNjarBofZ2ak
mQhArhQsAtQC+pUW+O1PmNk8Yd3L0OULCOQppwQzZkniHdplliMjgSxbdnPtbiGg
u0F6NLgORxr4dTFPz2HJaklUVcNuIGeQ49fgQayKB/fNIKuqfJPl
-----END RSA PRIVATE KEY-----
`)

func adapterKeyBytes() ([]byte, error) {
	return _adapterKey, nil
}

func adapterKey() (*asset, error) {
	bytes, err := adapterKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "adapter.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _fakeLogProviderCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEMTCCAhmgAwIBAgIRAL6HAMXZ0BZyyTQqLaJmg50wDQYJKoZIhvcNAQELBQAw
GTEXMBUGA1UEAxMObG9nZ3JlZ2F0b3ItY2EwHhcNMTcwMjE2MjEwODAxWhcNMTkw
MjE2MjEwODAxWjAcMRowGAYDVQQDExFmYWtlLWxvZy1wcm92aWRlcjCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMjVLTiLSzQAachr/VMNxrgxk9CyZ6Ih
lOK7IKmGGowzdGjclfYLD5ERKeYkugMrxkZp2MhCgcybnSTMYztGf2TNAXpwA6Bk
FZf0LOnryHlayNMsXzAabl0b9Ec5XoPsZrOCieOGUUdhdoBctV3btP0qZ59/qF0q
YEgTBSxOeV5f16tTRoNThxw+guvG8EVcj5PRH4rfeMHsZGnm6dc6TsaEo6NBlgdn
jgCCdxiSH0cwXd9ob6e9VggbNlc04UJstrw2lUUUJXLq85XU9uTH6aLruFfB3SAq
QlkIMTOFO7r8HU0Nz2sjhXEW1DmWR7Whh/y3S8TZ9jP9oKZie7OX6A8CAwEAAaNx
MG8wDgYDVR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjAdBgNVHQ4EFgQUWQ2k1vQ96M6mLGfVaJXPxV359fYwHwYDVR0jBBgwFoAUi0uZ
DZa+H/UIsFItwZfl8E1ts0kwDQYJKoZIhvcNAQELBQADggIBAGovShS0VpVAsM9o
PR7PLsE9fyYNKvQ0GZWoFwOxPOML5t9z8774na6VMVarm/s793S1r2lgMTOE0gok
RqYuMrRsDPlUfnN6L+rQvBjcKvnOnApfnClX6X841YzZguBbUpNgkNarS3thZaJk
cg92it2095fcSKmhCccIKfxyIVTcHnpV9L6ylBr4dXj/NL+ShJHom734qYF+ot5U
CyFjUuvW+3Rd43haDZpMHpQEA0LOiOan0psUp3XNuLZmpX9EKHge+CnaWz5rBlV4
2YojPWClcKTq5ePHwhPZtE+XuAdjohZruJB+0k4UJkLYQ75Hw/7IdrC950Hu8i2h
QjPSvgzJXdZRs5x/bEvGcnngpxdIIfz/Z2N3X+I/3s1zSxvjL2S4lWJtm/nyBW8H
HjJgUA02CnRRq+YyzzY9usvZrnW5RHNwUW3KNNinFebx9vKSUGwMNIPZPcDNxIDM
AhxKDy2KE4Q7O8R4bJNTdGLN10i2+f57a4n/FEgh9e0JexlOR1RxL5sKsO8fghRk
bM6m+uhvq+/oJ0I8YYqGLdFizMzsKkjaAbJrGVkD7//LzdGdEPb58oZjEO1IOyAs
d5kdVhj8LuQFe7alNx5kQCxzJyn6ulZRD6AktH9GbsqqhW/+0TJpo+fC7NJVU60o
QQPB1HTySG86k4hbQxjqIryAcndS
-----END CERTIFICATE-----
`)

func fakeLogProviderCrtBytes() ([]byte, error) {
	return _fakeLogProviderCrt, nil
}

func fakeLogProviderCrt() (*asset, error) {
	bytes, err := fakeLogProviderCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "fake-log-provider.crt", size: 1513, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _fakeLogProviderCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICYTCCAUkCAQAwHDEaMBgGA1UEAxMRZmFrZS1sb2ctcHJvdmlkZXIwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDI1S04i0s0AGnIa/1TDca4MZPQsmei
IZTiuyCphhqMM3Ro3JX2Cw+RESnmJLoDK8ZGadjIQoHMm50kzGM7Rn9kzQF6cAOg
ZBWX9Czp68h5WsjTLF8wGm5dG/RHOV6D7GazgonjhlFHYXaAXLVd27T9Kmeff6hd
KmBIEwUsTnleX9erU0aDU4ccPoLrxvBFXI+T0R+K33jB7GRp5unXOk7GhKOjQZYH
Z44AgncYkh9HMF3faG+nvVYIGzZXNOFCbLa8NpVFFCVy6vOV1Pbkx+mi67hXwd0g
KkJZCDEzhTu6/B1NDc9rI4VxFtQ5lke1oYf8t0vE2fYz/aCmYnuzl+gPAgMBAAGg
ADANBgkqhkiG9w0BAQsFAAOCAQEAS92QdGpDFHZj3pT2BinN+z+pcuuw8ttg9Qm/
z3fHrJE5EKhre5G/mKXGjBfgab5n/mn+5x7+TF/ouJ+d99ZeitngXLc04sviy++S
bi0JY4BggPVLqqoqCkjuL2SaY29xFV29QfQW3kn+yhTt9OJ7e5gjQsdq2XPcPqNF
z18AfZP7nwruMk2nZBbbqpf/cP9DgC9bfyd/YAEO8igM/KSb6eILj1I1nokCn/zf
GOrqZR8RddaiH5p67vom6AyJejw+i89CJZE2Cz3E6V5ABOcVwRPH72G+PeoXKgpk
jnRUpuQTFFm45qUpElndOUGxTxji93hzRidHv2vDhDB3VQYe5g==
-----END CERTIFICATE REQUEST-----
`)

func fakeLogProviderCsrBytes() ([]byte, error) {
	return _fakeLogProviderCsr, nil
}

func fakeLogProviderCsr() (*asset, error) {
	bytes, err := fakeLogProviderCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "fake-log-provider.csr", size: 903, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _fakeLogProviderKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAyNUtOItLNABpyGv9Uw3GuDGT0LJnoiGU4rsgqYYajDN0aNyV
9gsPkREp5iS6AyvGRmnYyEKBzJudJMxjO0Z/ZM0BenADoGQVl/Qs6evIeVrI0yxf
MBpuXRv0Rzleg+xms4KJ44ZRR2F2gFy1Xdu0/Spnn3+oXSpgSBMFLE55Xl/Xq1NG
g1OHHD6C68bwRVyPk9Efit94wexkaebp1zpOxoSjo0GWB2eOAIJ3GJIfRzBd32hv
p71WCBs2VzThQmy2vDaVRRQlcurzldT25Mfpouu4V8HdICpCWQgxM4U7uvwdTQ3P
ayOFcRbUOZZHtaGH/LdLxNn2M/2gpmJ7s5foDwIDAQABAoIBABoM9Omxv9aF+zLB
N0Hvtogr/iWDDshMHNjwNwNmXsky33W+r0EUHDfQByRQPUSuB/EYR8NqRRX6VX7x
eCm3Mk0r/nYYU5AZi2eDh9Pr/rwnF4e06L//nbM8LgqTGXx5TLUaSLKXuLFOpiVu
YSREnIx+VKSu1XMITSbsOK6Pm1SvVQhdOAJ9P975fhcRQE6iloNvnwncc/odeWP9
e5Hu0o0xDViFzwCNuYA5qelNwzmp73rG+BwjStOY8dFGUC1gPdISEe3Ms4THWyKN
sWGPh8to+WUnbarAuNNLOfZlUFIJlZmJuQx/NxYbIrqFqUV+i0WRdS20ZJXhRhGc
SuskoXECgYEA8HdOasARN8TuLFfz2Y0Zy79JtV+OF5UzFZgfMZUsGyaqOSJSIqZ+
85TdWEMH7QjIp/4lc/1vHhyLG+yFI5jJ5LfkhgQYiQ44gbxciEo/9I0gNRijWnU0
/npHqoOJ6MZaCUsQgKV+7Nfd+l+cT/K5P76/2pIEqaU1OQiExuufkIkCgYEA1c5v
wJQXsAfco0qTqDwLFFrGCatJvEhqTalAGV0OVm+Xm1TX+dtzfOFLvNgE3X1mI+U5
I5+aWRRBAtSvJ7Qp0OSshboFx6ch7gM+bysNJC91ivOwTFYlIQ7IUWWXcbEHokNb
hF5X996wSdsrVL/APMuZ8g1LN5cRhfmkmAoGHdcCgYAofT5D9UEw7cTYzJpvqDWO
vA/SLVvElse6PBoMhDyf+bux0RiZYwV/SDKY+PhtrgvzVXTC+gpqvI2jzwh//OsJ
yvj8o9Xpxe430hqWjEIGkHi62AIxagjZTIeiq3FeM3/Xjr8hmjwr7xEeZljwkUMl
+51cVTfZxMqYZtnMkMIWWQKBgQCrn7VG8dl93SG4FgIm9mOyaBc15cAfmkVyp5yj
f3Yl3hflgRqJHyY6JSNFqGVnYeSehb7zIIemX8K7wfwDs/QpEZaHFcbT+A4dX487
b2RyGoKREoH/FNtjCNm1tQX3JjLJhqYswAp/FsuNzZefxPhMFOczTIaHTgWr9LOx
s8IrKwKBgQCkQt43CsvPCM2eo3FssvbEl+m4cXhJ127mc+4y5561e3wWmLXchGv/
vlgWfRcQM1cPENc8eBGKx8MPVD3V35pcpzcoeWF05hZI1boBck+hkW33sOfQFjMH
TjlLcp/v1bMw+DbEBTUWXxbws4jqog0Zo3lq1ddf6slJ46TJIt7Mvw==
-----END RSA PRIVATE KEY-----
`)

func fakeLogProviderKeyBytes() ([]byte, error) {
	return _fakeLogProviderKey, nil
}

func fakeLogProviderKey() (*asset, error) {
	bytes, err := fakeLogProviderKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "fake-log-provider.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICiDByAgEBMA0GCSqGSIb3DQEBCwUAMBkxFzAVBgNVBAMTDmxvZ2dyZWdhdG9y
LWNhFw0xNzAyMTYyMTA4MDBaFw0yNzAyMTYyMTA4MDBaMACgIzAhMB8GA1UdIwQY
MBaAFItLmQ2Wvh/1CLBSLcGX5fBNbbNJMA0GCSqGSIb3DQEBCwUAA4ICAQBE8DVp
YICfi5YeM+KEw23F5XHriDF900P5KeOQv/gBT49+lpXVE37+luJl/y1wCxP4qbv8
JOSYmW2pb0sOcWjmWbgWKkTMjIxLAJg8m2zXv8QBIas4V5L42ASw/4jGWhSnVMFJ
8qDk09dVGC6zSmgq8G1S9p6Kd6CcLTiBNUxkN5TRR8wO1BQeEZWZ3sTsysVEZ8QZ
UyuL4oo6JCwpCEhziyB0MVO3+T+C2mmcAv00/79ma0FCQMdVwmGl7EgDiHzV4NRb
xJuAM0BoxbxPs1pX8fCHczYZblkqB9ZUgY2rTUznj0hYq3qSa2NAD175S8sYa7P5
CGd5OCBzl49uE6xNB5uIIgddDptaag966hldLyF8kA0jJ6KubS9s0RM6WES+tKcN
utNZfPJ1CFO/OFAuYckonqvg8bGngZsHXjyRqFgiTgaOeU8343XwSwceFFB+OoUm
0DUif35e0xWta9vtYMFoOyml6ADL+vtpD31MNYaXFgllhsxrtMBKVV8ogBV2e02D
RZZHjnu18yNWVUsVWbWRpdQDkP7Rf/LLMHlsjAaidlo3tfrjFVepmmixzZpR6Rzt
8q2vYYAA18nQoMqQ1VZNvC5F5Xk80cuWWjrHdsXrORUB5JX/ujYJIEWlX75O+wKu
Z9HLcN5uILfkYU78O0/ZXVtlWID4mcN9+fXseg==
-----END X509 CRL-----
`)

func loggregatorCaCrlBytes() ([]byte, error) {
	return _loggregatorCaCrl, nil
}

func loggregatorCaCrl() (*asset, error) {
	bytes, err := loggregatorCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crl", size: 934, mode: os.FileMode(292), modTime: time.Unix(1487279280, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE8jCCAtqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5sb2dn
cmVnYXRvci1jYTAeFw0xNzAyMTYyMTA3NTlaFw0yNzAyMTYyMTA4MDBaMBkxFzAV
BgNVBAMTDmxvZ2dyZWdhdG9yLWNhMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEA1NrqN8mBMYR/WlIMzMnbrwaJImt2jD1uuDhG1NbmQ/Dd42rlupO2q153
Js8ODi2b8AWCaU1VIPBSSXbON0VuBDCajDVKcPkYnF6w6la7rjAYMKrX0cnCtzuz
5s0s6t9hB5sjEZTpXPfuRDRDgKKMDvsop8dY/mtIAhAC9GRo0Fs7JTBbzYaUIOS5
kGZs3tLEiauKr3iy0FCYMzOlvvSVSRcRbpYEhYyQpV4lTKWd6vE2Kdd7pw4KR6++
t0zTPEUIyFdMoUD/opm2K5ioTLBsZm4Y7z5YDDcoqMvW//YmDXbKvU8QgLGj2ZPl
S5qBkZdgscienzClz1dl7wVLDDt10Kcmgu8Zr3diDaXbwaJkSioolAde40A/Z0JK
Lr/OgYWCk6fBfACIlAspywClkKEVdgHKtCQWe/970A85h8Kmg7ZTVGR4qme/47na
tRf485FmMThBAilkVp7Xz7FvAxqDL97kskcHVoIZ5Kt1CijokAMqfolGMzmsSZAe
8JP7J5rS9jMJODrhjvpSi0F6L9SQkYbwUelpnENRCI+ThIFIID0ieMZbNiAIgo5/
slhSO1vyKczJ5rnkOWyr/fres5EQC4qZrqn2ssL7AoE1y6WfYS5RIF/r9NvZjfK5
YRM3oVyZS+PzEGlpy7gw/M4lX2E5SP566MsBBK2eGm8+ihpbBVcCAwEAAaNFMEMw
DgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFItL
mQ2Wvh/1CLBSLcGX5fBNbbNJMA0GCSqGSIb3DQEBCwUAA4ICAQCdAF+itScsC3Ar
MIWvkl/Ex3ngzzQ72Nq1yp281TvyFj8pVAblDfOjBqid57vPnIEfyjh8jbCfl/VW
GG08cF1E6F1zeaB1I6vFn0Rk+Z7k1ZYLaY3i455GKJJ1jiAXyLwIYC8PMZ4fJw9J
j7VqLkqZ0xkX/OAt9H0ighxcwdl/GQhE0u3s9b7l44/cOa10nE0XthoJbPmUxbjx
6d0KwfVLVltrPfTN5lXlpOdOhnViqJOLeUOG8tGTdDJhbZTOH5KvPmzUPWhO+0EK
2qFAaknosbR/nF3Y5H8m8FzddimeG+P2EZZ+ITwdnmnxnlEV5OY37TxRnhSvi5wf
c3PBd2qfvf7HJtMJER1Con3Rs1pad7RKuvGsj9dnhXJzLrrkTvaHCI+gV5uqBliT
tdvkV+LtSPVmg5fczrztJbZ/+b+h2PrLa4pqTpjanIy0q1PfJtrMdVg81WGi4YxV
CBBIwDjv5vlrse/dPc0lQk0LuZJFzUAxN2M/2M/g+bioo3mtsy5jIrXYbw+n12Mq
asolsSC0ypjRQLVV4Dwbxbkx2qaOxI8KiBJro/n9kLzKlrJAMs4Hh50D6wyBuGO4
uEwW584OMaFqZBkCMv8q3mizmxH0r6A+0fLHBk9ApgY2TeKjYOK1yqy6F7bnzX2Z
PmpVkuACpDUVEEmx/ldFgLJnIN6V5Q==
-----END CERTIFICATE-----
`)

func loggregatorCaCrtBytes() ([]byte, error) {
	return _loggregatorCaCrt, nil
}

func loggregatorCaCrt() (*asset, error) {
	bytes, err := loggregatorCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crt", size: 1777, mode: os.FileMode(292), modTime: time.Unix(1487279280, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEA1NrqN8mBMYR/WlIMzMnbrwaJImt2jD1uuDhG1NbmQ/Dd42rl
upO2q153Js8ODi2b8AWCaU1VIPBSSXbON0VuBDCajDVKcPkYnF6w6la7rjAYMKrX
0cnCtzuz5s0s6t9hB5sjEZTpXPfuRDRDgKKMDvsop8dY/mtIAhAC9GRo0Fs7JTBb
zYaUIOS5kGZs3tLEiauKr3iy0FCYMzOlvvSVSRcRbpYEhYyQpV4lTKWd6vE2Kdd7
pw4KR6++t0zTPEUIyFdMoUD/opm2K5ioTLBsZm4Y7z5YDDcoqMvW//YmDXbKvU8Q
gLGj2ZPlS5qBkZdgscienzClz1dl7wVLDDt10Kcmgu8Zr3diDaXbwaJkSioolAde
40A/Z0JKLr/OgYWCk6fBfACIlAspywClkKEVdgHKtCQWe/970A85h8Kmg7ZTVGR4
qme/47natRf485FmMThBAilkVp7Xz7FvAxqDL97kskcHVoIZ5Kt1CijokAMqfolG
MzmsSZAe8JP7J5rS9jMJODrhjvpSi0F6L9SQkYbwUelpnENRCI+ThIFIID0ieMZb
NiAIgo5/slhSO1vyKczJ5rnkOWyr/fres5EQC4qZrqn2ssL7AoE1y6WfYS5RIF/r
9NvZjfK5YRM3oVyZS+PzEGlpy7gw/M4lX2E5SP566MsBBK2eGm8+ihpbBVcCAwEA
AQKCAgAmhrEaA9jkc4zxdiRm9KpUlaRAnJ7KZ1wg796yK2tmJLSksvZ9vLq1bdW3
KobqvgqZeQXPtXWRDq52KZDNpD1zeLCgbAzbQdrYgrMW1zgFISNfu6xwhko+DApV
3hEhOelADS5dwkwyzZVMtwD4yXL8Sy1ioMxU0GoqJWfDgGEQRVMBOi2Dl7Y79eo4
XrGZ6yAzot7pP7ltxwilS9XWKELVBd3b3D9ZRMXxiIbLxrY8jgg1rpDs/beSnhaw
6rDZGc2rJVHzZeZfMd8tKOZdaxlTuN2+f9RD8b/kPXDex1i/2x57AVKFWKHFgeVg
t8h356RSyXMccRux2anTh2u7/Q8nrkumLmQQY2e6BRqRVDZWuKifq9/5AQn55FZy
XUzRJYR03umhkzWgagNtFbp8R2sXpcsoH2FK4iJjz2VScrNi+XIIxnaqcxT2BLtR
NgDTb1oa50OD56pp+eW4q2F0Q1t1Sp0zFhzyTJOBnYyi2Q7Kjmx7noZ1CCjyxBQV
aF+EC4XWTCo/3g2Af/0z146DEv9TbOFkAw2zvhHPSsrWAg2JpD2BLg0xFDSTq27w
AwPVxKiGrLy8ZZMGLl/8VmuHoCNvUVBTKCd+rm6n30OykBPK3TfwqxmkRpgBWB2K
2p+5jfPNWuA0GlHEAPMxKyfQdmVCX7DJPLuN4QrL1yOkiD11AQKCAQEA+P82iYTD
KTrnWfpAfAwzVPW5LKRwqFw7qlpmPrp4TzPCx2wcHlCydOPRXP1JJCHZoC3EsgcJ
NoKxTrbW4tAJ8Qp0xF9pLxed/DsE7Bp6gbQm2tgNeYmaxR3C6LA8MH2mfJsfcJ95
phEAIo2AGSMOQ+emNU+hMLC7w4MM/q7EQUrHjgxkGV/nW7lz0njjPQAUuXFMkVs6
sLJqy9IkKtKFmp7c6ZjwF24QghrpHMmCiZQ45EYHG0qcUksVRgXWKCuGOHT7nd5U
m0MyjtkKkQx3c56EJQlQyXNyCGT51WdBolVuF8ZFp9Kw4Dt7vae5oXGg3wU+McMR
wdU1WKX+Sp4PQQKCAQEA2td6y9RmKn9uMChTYU/eOXsEMZ+JwAIDA3LPoa8cdKTU
3GUTS1Zn1PMUEsSuLM+4KL/8S+q2AJUy6ewvTGV7WYcnLdCihCmFoO9INM2Qqutx
G0ZxfSyUIj9IMiWOT1TQK3WxU1Gf932Z+CxgMzdWCjZ/3XqdofPv7gq+JqbOPf8Z
qs2FcCnDTEriPYhXvRuMubW7e3/L42MmwEyweOnOOC3FIsLliLf4wpJg0nqBIXp8
eGPojC6TGii9D1HZk0yOMkDq+ejTxqicwdAtCTbefC4lNQIp1Dzuzq+sFTpr8x/t
MS+eod5GE9fvVqcXm9TC/jL1oFjIepi/wO2rtiSGlwKCAQEA5xFf+QpdWhuxqoxT
30orMMK/zy/i5DqDnDk7/SZqk4WDUjF/fpqAoXzxQ4xBnehT3xPaHyPsZsut41BF
5kINl8SOS9YG9I7EK9hRXxHLciZOkHRDPPB30kkmIW26zX0tTSFfcdJsv7GzIF2T
7L/dcyK72WlGOrsn4+3v10E0GytcOPRCyFF5kGNvmnhY2LkEgnskBRhWRLet5+vh
aGPpXG3ksFsfI38ejr6OagqOu0Hz8dMSsT7yBmRrH4o3DRwm+KmG/x/eAB/CAVJl
PeoFyCPomb4lXG1n+2ZJesLR4+XHvwRei7k4Lz7EPGI0ICAknBJvfxp5lhlX4iZY
78HygQKCAQEAlSYrAOR/xRMYjCXPvhDrCg33a8Kp5Xz5hM4pCK8KG82DbbpNjhkT
pyUMV0ZI1y2y+8LtNuh+pqMJEjjwe4bmrLvaTfVV7fFGq8qpUaOQp4zTh51ZF9Dc
HQM4N0U1WogZYKVT98830Tt/Ro8n+YALWeaO+unoqUpSCdC0jC8/fS1x1uE/wpQU
ENkwnHNiKPav0Jo1bxRIZ29aJ9GcrKvc6pj3NJvUSHvqROHyr0Di5WhPkNW21mOf
ykJdqCVGvod8mm94Nl8ihtDAFa/GIfONauEgZqJU09u7fo5oIAezLv5hcBZebT/K
TxfqfQpgoso9I3ajxWb9K+ETP3A8iWUXfQKCAQEAiFeqSLh5zhKIQZrNEzGyiNbO
898hnzYrsWT1GRE2lDbhD9XSplMtPJp8jCORinr0I5B+67K9oylqAn1VjWBrGAJQ
a1t9xRzRTP9e55cwVCzYnXZjINdF/kzlc0HEBXalTNc1HBCWzJGUgcRtykjeUlkM
g78n6Mp7kjqd2X+uHZU0Edb3dvntExGUCUVItEUg5SWHZQeUlRBrUyWHaeUVO1Q2
2C63zFrXqqgTMy+icI9fxeAgP3Od7jL6Q+DpIXzpiPGHu8WR/qF2vepSlX8a0iB9
VdKUXgwWEuCTupDdY48VDc1eR6NFpLPmSQZyyz1GolL4+C51odoJJblIODNjrw==
-----END RSA PRIVATE KEY-----
`)

func loggregatorCaKeyBytes() ([]byte, error) {
	return _loggregatorCaKey, nil
}

func loggregatorCaKey() (*asset, error) {
	bytes, err := loggregatorCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.key", size: 3247, mode: os.FileMode(288), modTime: time.Unix(1487279280, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalableSyslogCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICjDB2AgEBMA0GCSqGSIb3DQEBCwUAMB0xGzAZBgNVBAMTEnNjYWxhYmxlLXN5
c2xvZy1jYRcNMTcwMjE2MjEwNzU5WhcNMjcwMjE2MjEwNzU5WjAAoCMwITAfBgNV
HSMEGDAWgBTOAFfudObFa4DKfq1NNIyXt43bsDANBgkqhkiG9w0BAQsFAAOCAgEA
xCIlig5LiHJm8spVd9dgcsq/QhXzPthqDPQJ+n6lbK2q+vBdv+V5z7qjq+LcI/VR
FjII7DKeYb1e2quyDGmWc+x+9PRXHdBRDuTDLlfzUM/p2zMfoxupnce/5F1bkopz
iI3IFEbcCiVHlaleC21iziiTFWpYnUrJNyO80ImJ51EeToEclYmnOOJmdG5VcEPu
fbxkAf0ZsmaLrX9BBuGxKO88smUZ5vZFEDfUdhr2zhqOaEGR4Yfnd3NbGnRjuZ8S
GCSXDmTzDL9mqFjwTwp3Zw3hz8EzGSd5VNFkI3ou5e5v5tFaQXd2I9e+Blf0HrDT
XD12TW+NQWh5/wRKDXMquje0d+0Mx6B7OGZyCw5rA4gUSFeXowcm+tFjAjYcq5kO
ljFNigCVuhYNzGEOliqVisLEtI6sYZTPxBxbxTeRoCmMQ7Qc+2x6saj1yg5qbtmA
PSOJ+dM6jfNMwsmuhA/VHjPLRIQa6jn2Ky/PdTCFqAASgSoUOZouqZN0dswR32n4
fOR9oQdmoa2t1+nRHJUtk4jEjZAs5682UhGDhtxSUdKcBp9Ht9+xyTtpqrIAHeS6
/NO2VTlAukBsphMdELrc/BACtVJmLRXgP4T+qnCXjDUUNgq546U800+Sm8qw27rX
MQODlZcA0/TcksfNWzrb/el/vllibJwXm+rkeO2nQGA=
-----END X509 CRL-----
`)

func scalableSyslogCaCrlBytes() ([]byte, error) {
	return _scalableSyslogCaCrl, nil
}

func scalableSyslogCaCrl() (*asset, error) {
	bytes, err := scalableSyslogCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalable-syslog-ca.crl", size: 938, mode: os.FileMode(292), modTime: time.Unix(1487279279, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalableSyslogCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE+jCCAuKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQDExJzY2Fs
YWJsZS1zeXNsb2ctY2EwHhcNMTcwMjE2MjEwNzU2WhcNMjcwMjE2MjEwNzU5WjAd
MRswGQYDVQQDExJzY2FsYWJsZS1zeXNsb2ctY2EwggIiMA0GCSqGSIb3DQEBAQUA
A4ICDwAwggIKAoICAQDV5s5Y3arHjePkL40NVt2XfLXgRR0FZ8TvQfSAxif4WkAQ
yYls3U43XriuYclhHZM18CvH5jPwGM10lEVL/otQZUinrgOgwc0qSd0GQmtfpf0Q
wMRiuJNiv9fka12UujX95cRz+pdyaDndsa+rdbEHoL4WxhoLfHmhpNk9BAUCfsuy
guMBkmPHbX/eH/oSzAw3zJl4d8Hyq/icFI3ZzHHhnl2KTG+834q6psOBSGPTnw3t
6i7Nk9HR5oTAkzckpjj+2vczjJh2sCE17jUVGLXL/DSIqnFZvFMUZretSvR0k+Su
/OwXJf91GPQdvo4Ueky6CPcHk6Tc50PcFEMQ619HHBKkiXBNwBrucx+ABcoZg+E7
tKjgqcUG0fNV5/ZlxbEtaekuVetzBquzqUQulx+RwVchSVKeMRnO68eWEBevbIzm
gYee4CVfmAZx1rS6ujEGhqPzaZHk2I2/8Iz0MbPbgsrTEiQmvG0hpuRoc9IOq5xO
bipNEbqEkpZ87C43dOlGHbvJNV728Esw7gEpvqp1VXXOUapID5eBqwm9yfjhOrqz
ayT+nmUQ2Tsl9ZDplq4Oqd0mOsBOun0Lte20jMZI1oc548woyAsngBtDzW8wAjsK
avspX44nvJbQzxFk9WMQu4gILPbUmlreFoDvHQ/uoFuo/3fEP49WgfCoNXA/FwID
AQABo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
HQ4EFgQUzgBX7nTmxWuAyn6tTTSMl7eN27AwDQYJKoZIhvcNAQELBQADggIBAHSH
LvVsvnXVGo7trySCAm02WfZNhBC2zKpoHqyt3g7TtznY3Sb+hORHpbStPTlnlKaY
8wuv+Q3TNmV29kNR1EwINEwWJfy1ZAIQ0AyaDsTwtGX5Vvj0FJhZZUsHPkY2sImM
rdwcvRIw+yR8pq2/3IYga9DP43EUut3k4hM0ohCcz8VtT3iIPyjugzzJwVpgFllE
0+9KIdqbnKObtKaiIYwmGrAa6uOYQsZX66zLukYGS8g8iuwqJnBLXQ8+/YsAZ5Ve
lZEH0uyuDtEShZQwBn0E1vGMpyV6ApwXL5q/3jfkYKxYSMwX/uehpZ/YfcYrjCZa
Buqh4UssUeq/jZbwk00QccijL9EesuvsqWHof2LiQuIDk4RU8cY7AYqWEqroOeBI
o3uNirdB4FLB8Cb4vIxfx5/COhe/SfUHJmLwnHjoeiljXBeMMI1J4eTAAt8ifI7H
f1ESJXZYzDwTeEx/tswBxThIyFhmIi7HTXJQyaQNWmJGcGbnHLeGIyDhHJKYffit
jksjXe9osC97UtSOYZ7mB3w+WnEiKgn/0pK2DSsHHY/+2R3XUmCG5C2Zdh83kWM3
Zou4B6HEjn+yhf9zZY8yvopupljrx1VRtKQQu0ANjXreFrXmKG1CPZuRe0zd6W0Y
QsJnWfa2rKThGj64CvmozVuLuNyFMB2so2v0RSeS
-----END CERTIFICATE-----
`)

func scalableSyslogCaCrtBytes() ([]byte, error) {
	return _scalableSyslogCaCrt, nil
}

func scalableSyslogCaCrt() (*asset, error) {
	bytes, err := scalableSyslogCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalable-syslog-ca.crt", size: 1785, mode: os.FileMode(292), modTime: time.Unix(1487279279, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalableSyslogCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEA1ebOWN2qx43j5C+NDVbdl3y14EUdBWfE70H0gMYn+FpAEMmJ
bN1ON164rmHJYR2TNfArx+Yz8BjNdJRFS/6LUGVIp64DoMHNKkndBkJrX6X9EMDE
YriTYr/X5GtdlLo1/eXEc/qXcmg53bGvq3WxB6C+FsYaC3x5oaTZPQQFAn7LsoLj
AZJjx21/3h/6EswMN8yZeHfB8qv4nBSN2cxx4Z5dikxvvN+KuqbDgUhj058N7eou
zZPR0eaEwJM3JKY4/tr3M4yYdrAhNe41FRi1y/w0iKpxWbxTFGa3rUr0dJPkrvzs
FyX/dRj0Hb6OFHpMugj3B5Ok3OdD3BRDEOtfRxwSpIlwTcAa7nMfgAXKGYPhO7So
4KnFBtHzVef2ZcWxLWnpLlXrcwars6lELpcfkcFXIUlSnjEZzuvHlhAXr2yM5oGH
nuAlX5gGcda0uroxBoaj82mR5NiNv/CM9DGz24LK0xIkJrxtIabkaHPSDqucTm4q
TRG6hJKWfOwuN3TpRh27yTVe9vBLMO4BKb6qdVV1zlGqSA+XgasJvcn44Tq6s2sk
/p5lENk7JfWQ6ZauDqndJjrATrp9C7XttIzGSNaHOePMKMgLJ4AbQ81vMAI7Cmr7
KV+OJ7yW0M8RZPVjELuICCz21Jpa3haA7x0P7qBbqP93xD+PVoHwqDVwPxcCAwEA
AQKCAgAbKV3Whv9iq6/ej/M3WGp3DA0EV4Jh51VolFV57K+yp7Mu7oiW3FtMSKjm
69/ohxrkZIUKsz6xJFUikpliFwaVxOa+9Cfdx/5Hem2ol9KOqMND11aYuptslLPT
e5a8hhDJFt4lZBLLIlUGw8Ns4FsEfvLkbW9tOfcwAYDccKA6OuOe3WP6FR66ejsc
d68HqAV9KGvskjh8mj3NhAanO4DSh4uVPjOKJlC1duuohQq4GqBoL66VyEmCf+Un
lwoPi1P9eMyfLSFHIQJ2mLMA5MxhBLufBxWxsWpTUt/MD5KPIyCM3+0S225e7jZB
eKsOCqGnle/YdHUg3/UMAz6o7VqBr6eZ0fueiAUVMKovsF5EKBlsGOOrcBSpIEz9
DR89gmFGx29P3VdiqsI7wMVWFPioNApxWEVcpLOy8Zfh96Z+XbHTpdZy2ngGpGXe
hcVnZDHz3+UZc+dXcfHIWdH27WC8t/xA8auIMeHrM/Vr0KoU/xq5fBtS7m4ctKy5
2hC4sUfUEaRBYLNk6iZueKBopHCLjEh0LYAwVyUPOMH0sXbfU0xTf1w2H1nXDvfD
P6CUIVc7jeYYiNEFukjfuOF8FX+S7e2y4Z8PErWdj8ogyshaqdhd+cXLxibQH6Gi
4J4Y+zCT1M6IHKgcqcGOiKI9o/PO1GH9xDOhS60L4s1NVI/HgQKCAQEA8VgWCkJm
DTT1+YbOLH4ACdGVKPFR1i4lJKniROf5WDgGsKE4F/3HpMlQIqxN+XifRYWgCgSr
4WtjMxbLhg4EVAMJWyK0cOuaNaBo7mhzrNjqVQ4C8c0VUBKUVbxOiJOUyCuyJBxN
QNXiCP9oeq+P1VjWZig5+/J/YGxoJiUXyqCMWVccoiNIe6wKLOwgazEG9VIBYaJ8
93QHfLZkmi6ZMWBDSErtzuLA9b1DKcU5tHLI83YFT3uUN+McL4FFa0z176VwdkGA
2TguI4Y05gpKEqcur0tnSxoXSSPYCfU8anBMRy32IK+xmQmLDSj/vuUQxGK9d9kN
JY6ku/FGhIFDoQKCAQEA4uQZ7Bfs4L7N6Ir2zL9wtMSGLLtNAP2mheiCpTNhPfPq
t17+SAqV2Dpp1PDgPLrIgMgsE5nWr2bRcRz2msIN5acL21UVOgrLVtD/A17iKmdN
6NWyqs8a6+1ZY/zcEVuFRr4bpCBHUg8QL5A6LASa+nKzcAUOqbaye+MgztDeJHQ+
LrI5X5dNUt2EbBdGFdpFEVP1my2S4dTmd98lpc5RUkUA2XaJSZK57juuBwxbG0iY
bVLP/ME8WK9oPfkb66a3E+XiTeuYjyI1TdN8olRNyBv0RtwxMXl4Sg0SqeL0JYJk
zduMsIoIrVTCwfPEHFqlf2pddzYztVbnDr5Y1f+HtwKCAQEAuhoapL6ewwBbzJZO
1bAzh169jlzHpkjfC26UtF3MwGIzhnBLOPTQxhkWWiZT2lNRPeLUjeUcRS7xx6uE
NVMJs17EECqqyYhj2YZgY7bXvCloST4MtzhVfvFUwOf8BwUGbXSEYaQRTjWfnyCU
CEbourNOYGgUjltoLYpqpT9lITK8BwhNZBmhAvyevBU4ym971h/uQMNzab1nKJvc
56eXKaP5Pf3JcwcXlGblK4iR/rukiVgwsCGzIYVXbqpYRW2LF8iS+B16pgXUTkBm
+hxlEg0oyrNya08rNZMWPFeGxuzhZOHkMUBJyqC5QOSkkSdBzq31PD17DcL49JQQ
tIyZAQKCAQB/jTJResXNNxb00yKZyknnJdA0V3ubwf0arLK9gpv5QyXBvqJ/B4xj
ybrzXhMBsRPE6kN1JXf+lXPK/jhYmh1L7NQKktNjFOxpOwcR8wZ8RiUTbweJZPLC
jWVCg8WH8IaFVZyecRMHO7aitpctZc1mXJMpt34dxLqkUPSBsAQiREMs5z6/0YRD
wIqQZakd4d4QNr4NZdp8IL8LxqQYiVtIP8iReEUH2neySVS1W6ngNbiTRQnuEwgE
519X77JVkRy9D/BgU8EpPlbvEKSxcWlkxOpX57O0F5CbOKw0W4VbjOl0nSeDm6Xz
I4J1nL+0HPWLItW2jf8Vw+wTasjwTT4TAoIBAQCp8aCmKwLMAV0iooU4ppgcdVb1
aGwKLZ7dooDUitfI+dGL85gAhBG1Yk3IWxRDh6u2/FXme/FDlpspC+yBQYlnwobA
UliPG+j54OJO0P3dhR1otARoX1mm345NMcTedIsckYkxgv3yFwW5A2X9gc5YLTat
ze2V4J2TJOChIplpURWQP7eg9Y5neQkfHJ1r27K7ZD9i5j0A0lZoeM3WQaxlvuHu
JuCSoqI8uZSEu5beZDjU1C26zXU6VxReC/OLGwA/4XdLmLu8YmL2Tx3TGhl0m0ZA
JolzZxKKK27GGNAycvEOVe1ml1wD7wTpzOQGSpfeU7m14s5V60E+Qd58d94W
-----END RSA PRIVATE KEY-----
`)

func scalableSyslogCaKeyBytes() ([]byte, error) {
	return _scalableSyslogCaKey, nil
}

func scalableSyslogCaKey() (*asset, error) {
	bytes, err := scalableSyslogCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalable-syslog-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1487279279, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schedulerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIELDCCAhSgAwIBAgIQdpMrJ7Seb42Or2w5qJvAYjANBgkqhkiG9w0BAQsFADAd
MRswGQYDVQQDExJzY2FsYWJsZS1zeXNsb2ctY2EwHhcNMTcwMjE2MjEwODAxWhcN
MTkwMjE2MjEwODAxWjAUMRIwEAYDVQQDEwlzY2hlZHVsZXIwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDDBpLqns5dcRb2jqoqyKk1lXzsS2jB5+WGgmf+
Mdfge9OK/Fy8HCM9YJGYGYs8JX00fArO1qlJVP6ueUDhCnpGUPSwOy8niKmJ/XBk
ALrZf8Q/OM1NIh9oBFICc8UvHbpLPdI3NrwHsvyhPGPBSdGWZfoqfcm+McClQok6
xEy1NbXwJ/uz1KPsb6z9ufdmRiv3YybIE8eH7v731SX7oofcb9HJ6dmTHBkGMTQP
7GuhD//3GVdymZsaAevWH9sXgDRBDsLqZBwGrskNC6OeTl4tgQFvdRs9tX+Zk/Hr
l8OLIuYbkvZ5FbJGbHql+4WseR9gHNvLQTCKUSDI3K6rj3MfAgMBAAGjcTBvMA4G
A1UdDwEB/wQEAwIDuDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYD
VR0OBBYEFHJqwPiRarzcGJPAZAw8uBaqxYLwMB8GA1UdIwQYMBaAFM4AV+505sVr
gMp+rU00jJe3jduwMA0GCSqGSIb3DQEBCwUAA4ICAQAftJNK4SCy4nroJ/Trrujw
fcruXPJ5XW0hZ0bi0v1+lfn07efD7mAY0NiUfdIgCioEdWB2qFhFA+J+5bnRBfMC
gac3Cw9qdn0enz/DrwOErlhtGL2ibZRxroc7p3fRNstGBeZnnP0JQnrNDTn3AAPZ
QndWItC6aTh7fEZgEtCC9gzDN5i0Gy98HwSe5jUjKHZDgSPadxH7EtVbUC7TTfiN
6G9z/o5Ae0xjpMgYwfaH+uGVLe1IjZqH3FEOfCpT77WJ3Y0gcBxpaeX3CSCthvip
rwnOpoNQyHtzn60kNyP8pgNJUCBJCNcqVZOf/3sekSsTtkFFeUiVv7PPLiBcwg1t
+Xl0AU6AEbtWkTPUgHM00Uk5Blz319+zNwS3LgbKpjFefB04jeLbLOSzEu9e2Cxe
2bXzz/A11oglhYKmTT4D3lQgFLwpZqc+RIWN3vF66HgLbftmycTaQOys8kHL7/iO
wY/whvYnJufQVeqZwgmCmZck1ZPUX04eNyvI3O0HIwGs0hy5gzasUKd2ymkD4Gao
1OPwTEEtta6DK/gyw5of9AZ5TR+3/6cyAnY1rPvqwCVRVC7Ydmj63BsgXW/bWeOh
gQuqXXyauha0QPJrSpwlis4w4b1UmI3/IBZWR4CznfdatvI4lUbhWJ2MeKw2QYCL
5PqOmycDPmkwkSnMyidccg==
-----END CERTIFICATE-----
`)

func schedulerCrtBytes() ([]byte, error) {
	return _schedulerCrt, nil
}

func schedulerCrt() (*asset, error) {
	bytes, err := schedulerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scheduler.crt", size: 1509, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schedulerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICWTCCAUECAQAwFDESMBAGA1UEAxMJc2NoZWR1bGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAwwaS6p7OXXEW9o6qKsipNZV87EtoweflhoJn/jHX
4HvTivxcvBwjPWCRmBmLPCV9NHwKztapSVT+rnlA4Qp6RlD0sDsvJ4ipif1wZAC6
2X/EPzjNTSIfaARSAnPFLx26Sz3SNza8B7L8oTxjwUnRlmX6Kn3JvjHApUKJOsRM
tTW18Cf7s9Sj7G+s/bn3ZkYr92MmyBPHh+7+99Ul+6KH3G/RyenZkxwZBjE0D+xr
oQ//9xlXcpmbGgHr1h/bF4A0QQ7C6mQcBq7JDQujnk5eLYEBb3UbPbV/mZPx65fD
iyLmG5L2eRWyRmx6pfuFrHkfYBzby0EwilEgyNyuq49zHwIDAQABoAAwDQYJKoZI
hvcNAQELBQADggEBAAjLkpuloc+HbYuYJbAXMzQu7zWhISZZ4WB+g5mOTYPr3PBJ
9n4AN8dMC44rXsfylU9r731TOtJTB6qntCghkJ4UKQbqm3DHZmcFGhwxjmWVDBCF
X+xOVy6e22vV5AT9LcMt0cIjPbLs1ym+4fS6SRRsKRsdgmj13L9+QtBVCl0bHTCg
3agRucEs+bpjsiDkW1rE83QPmzhmXdO3cCCYo1v0EpbwRu5kCPBow+V/24whHC8s
6FIkfphqL/qedAgo9j6adiEECA4roPvVQujMSpmQsq4w7TY13Yp33QHNRRABnRDC
4lcqAn4PadJVCUI9/R83TfGNZbO2sguPTC8ZTlg=
-----END CERTIFICATE REQUEST-----
`)

func schedulerCsrBytes() ([]byte, error) {
	return _schedulerCsr, nil
}

func schedulerCsr() (*asset, error) {
	bytes, err := schedulerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scheduler.csr", size: 891, mode: os.FileMode(292), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schedulerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAwwaS6p7OXXEW9o6qKsipNZV87EtoweflhoJn/jHX4HvTivxc
vBwjPWCRmBmLPCV9NHwKztapSVT+rnlA4Qp6RlD0sDsvJ4ipif1wZAC62X/EPzjN
TSIfaARSAnPFLx26Sz3SNza8B7L8oTxjwUnRlmX6Kn3JvjHApUKJOsRMtTW18Cf7
s9Sj7G+s/bn3ZkYr92MmyBPHh+7+99Ul+6KH3G/RyenZkxwZBjE0D+xroQ//9xlX
cpmbGgHr1h/bF4A0QQ7C6mQcBq7JDQujnk5eLYEBb3UbPbV/mZPx65fDiyLmG5L2
eRWyRmx6pfuFrHkfYBzby0EwilEgyNyuq49zHwIDAQABAoIBACoD9YzUT7Mz1PWj
QKfc+Q9ROEuT52q28ezrlUnfJRn4s1djDPt9uF3VuygggK2hifrPqmhrOKdSx1eB
SefxoOwbLsv0xDDpMVVII3l36slGzFmufBRdAJUhMSXUGSwQZH0nQW2hvhqOhfya
jQcsRxn2uFGFLfxqrY0s63GcrsXu/rccAnz4HsiFjbJrl+1ZjGnL5F9I8a+M33pq
C0eGpvgN7CW0FgUPPaj29Q5SwzgyGFOFd2kKg5d6OARGEwWU+FyaIo72H7fwRSm3
1E4Xupes/DJyBOOEgsDlwPv291dK7Phs/am0NIdfAESa7hLoJ139yqTChIzQHLro
19kCIQkCgYEAzUw0pNmUSixcYPvvTJ6V5R3BwJUVrYR2WVMteRuu6G4khVxkMFnU
SFx19bolJR3hrG0MU/22dfXt+zq+KUb3OvepnQxOoNZkrMCF/DONSK8nz2TLUJCD
mtpDNN8FMjMDNC8quymJ+XV7fwsKm+akko+rM2NpP6Lh6h/7JcKoZxsCgYEA8zDt
vnBQyETULUZAVbnKiR1mnQ/rm6CbkWcykaF9UsH0jadpfVMTumTIrbsCqioYQC6C
FygMBTYaqGFABNPH35DTGFJLiYw3hhjUPGM6oDFjMDPatGa1y8XQv+tEBCFzxDY9
XfKWZbDEKwbIwewoBeBTCknCoXtNwDlFR/cQUE0CgYB4qM9QDCkhpwzsW2X7zEEh
FeooO/cvsmi0ezSAt4qHRSTl1LV1zXX8yYryz2LBe9yFMNpMCxPQJKioPZBCRllM
KP9hNDiKQzeMaOLWpZ3mGDv3oq/0O9t9icZyLpmpNV4ur4IX2oQjP69DrcOgeWBE
W3gtjcHwCtVoez9qpAvB/QKBgCLH46ix7YvG9EWJX5gjG0li8BMUfNDkNnukM8JK
Q187qBs+T0MCR7cHxP+72FS38oHzZN2k95sjMsrUJdDK7TIXR2maE32XlTVThb8h
Pfg9N/9j2yqj6eo733AjWLXyhtkQHNS75jCjCFtS/BFoEg1NGPNGu1RXCzarujHh
ru6dAoGAcaJVcWdiaJ96CWXWxE3AL6Rt8Hn6ecKS4bmJ/1r+FE0nb98m+Igy9sJ2
M7aR/rhFyNOhz9gdFTndngpUH2wT2GrmDfDUYuY2O4Q1s9z4RHweHGgpJ/8PcMtq
Y+6jy30pBUUHE+0nw7OGOYh/OS9kiXvdiZ1QSo7A2S0EICuS034=
-----END RSA PRIVATE KEY-----
`)

func schedulerKeyBytes() ([]byte, error) {
	return _schedulerKey, nil
}

func schedulerKey() (*asset, error) {
	bytes, err := schedulerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scheduler.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1487279281, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"adapter-rlp.crt": adapterRlpCrt,
	"adapter-rlp.csr": adapterRlpCsr,
	"adapter-rlp.key": adapterRlpKey,
	"adapter.crt": adapterCrt,
	"adapter.csr": adapterCsr,
	"adapter.key": adapterKey,
	"fake-log-provider.crt": fakeLogProviderCrt,
	"fake-log-provider.csr": fakeLogProviderCsr,
	"fake-log-provider.key": fakeLogProviderKey,
	"loggregator-ca.crl": loggregatorCaCrl,
	"loggregator-ca.crt": loggregatorCaCrt,
	"loggregator-ca.key": loggregatorCaKey,
	"scalable-syslog-ca.crl": scalableSyslogCaCrl,
	"scalable-syslog-ca.crt": scalableSyslogCaCrt,
	"scalable-syslog-ca.key": scalableSyslogCaKey,
	"scheduler.crt": schedulerCrt,
	"scheduler.csr": schedulerCsr,
	"scheduler.key": schedulerKey,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"adapter-rlp.crt": &bintree{adapterRlpCrt, map[string]*bintree{}},
	"adapter-rlp.csr": &bintree{adapterRlpCsr, map[string]*bintree{}},
	"adapter-rlp.key": &bintree{adapterRlpKey, map[string]*bintree{}},
	"adapter.crt": &bintree{adapterCrt, map[string]*bintree{}},
	"adapter.csr": &bintree{adapterCsr, map[string]*bintree{}},
	"adapter.key": &bintree{adapterKey, map[string]*bintree{}},
	"fake-log-provider.crt": &bintree{fakeLogProviderCrt, map[string]*bintree{}},
	"fake-log-provider.csr": &bintree{fakeLogProviderCsr, map[string]*bintree{}},
	"fake-log-provider.key": &bintree{fakeLogProviderKey, map[string]*bintree{}},
	"loggregator-ca.crl": &bintree{loggregatorCaCrl, map[string]*bintree{}},
	"loggregator-ca.crt": &bintree{loggregatorCaCrt, map[string]*bintree{}},
	"loggregator-ca.key": &bintree{loggregatorCaKey, map[string]*bintree{}},
	"scalable-syslog-ca.crl": &bintree{scalableSyslogCaCrl, map[string]*bintree{}},
	"scalable-syslog-ca.crt": &bintree{scalableSyslogCaCrt, map[string]*bintree{}},
	"scalable-syslog-ca.key": &bintree{scalableSyslogCaKey, map[string]*bintree{}},
	"scheduler.crt": &bintree{schedulerCrt, map[string]*bintree{}},
	"scheduler.csr": &bintree{schedulerCsr, map[string]*bintree{}},
	"scheduler.key": &bintree{schedulerKey, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

