// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package handlers_test

import v1 "github.com/cloudfoundry-incubator/scalable-syslog/api/v1"

type mockBindingStore struct {
	ListCalled chan bool
	ListOutput struct {
		Bindings chan []*v1.Binding
	}
}

func newMockBindingStore() *mockBindingStore {
	m := &mockBindingStore{}
	m.ListCalled = make(chan bool, 100)
	m.ListOutput.Bindings = make(chan []*v1.Binding, 100)
	return m
}
func (m *mockBindingStore) List() (bindings []*v1.Binding) {
	m.ListCalled <- true
	return <-m.ListOutput.Bindings
}
